name: Update Database

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight (UTC)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update database.txt
      run: |
        # Check if database.txt exists, create if it doesn't
        if [ ! -f database.txt ]; then
          echo "Creating new database.txt file"
          touch database.txt
        fi

        # Append new data to database.txt
        echo "New data entry $(date)" >> database.txt
        
        # Set up Git configuration
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        
        # Add changes to git
        git add database.txt
        
        # Commit changes with a message
        git commit -m "Update database.txt"

        # Push changes to the repository
        git push
